# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^(.circleci/config.yml|Brewfile\.lock\.json)$
      - id: debug-statements
      - id: fix-encoding-pragma
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: forbid-new-submodules
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: detect-private-key
  - repo: https://github.com/coyainsurance/pre-commit-scalafmt
    rev: 1.0.1
    hooks:
      - id: scalafmt
  - repo: local
    hooks:
    - id: circleci-pack
      name: circleci-pack
      description: Generate the circleci config
      entry: bash -c "circleci config pack .circleci > .circleci/config.yml"
      pass_filenames: false
      files: ^.circleci/.*\.yml$
      exclude: ^.circleci/config\.yml$
      language: system
    - id: circleci-validate
      name: circleci-validate
      description: Check the circleci config
      entry: circleci config validate
      pass_filenames: false
      files: ^.circleci/config\.yml$
      language: system
