working_directory: ~/src
docker:
    # sbt + awscli
    - image: leapyear1/sbt:8u265-jdk-slim-buster_1.3.13
environment:
    # By default, Java8 doesn't recognize that it is running in a docker container.
    - JAVA_OPTS: -Xms4g -Xmx4g -XX:MaxMetaspaceSize=512M -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
