executor: sbt
steps:
  - checkout
  - run:
      name: Setup DashO
      command: .circleci/setup_dasho.sh
  - restore_cache:
      keys:
        - v2-dependencies-{{ checksum "build.sbt" }}
        - v2-dependencies-
  - run:
      name: Compile jar and run tests
      command: cat /dev/null | sbt -v clean update headerCheck compile package scripted
  - save_cache:
      key: v2-dependencies-{{ checksum "build.sbt" }}
      paths:
        - "~/.ivy2/cache"
        - "~/.sbt"
        - "~/.m2"
  - store_artifacts:
      path: target
